### CREATE CLASIFICATION
# POST http://localhost:4000/api/clasifications/create
# Content-Type: application/json

# {
#   "name": "Ground Coffee"
# }



### GET ALL CLASIFICATIONS
# GET http://localhost:4000/api/clasifications?p=1&limit=5



### UPDATE CLASIFICATION
# PUT http://localhost:4000/api/clasifications/update/650d055db8b6303337f3906a
# Content-Type: application/json

# {
#   "name": "Black"
# }



### DELETE CLASIFICATION
# DELETE http://localhost:4000/api/clasifications/delete/650d055db8b6303337f3906a
