### CREATE PRODUCT
# POST http://localhost:4000/api/products/create
# Content-Type: application/json

# {
#   "name": "Organic Coffee Frappuccino",
#   "description": "Coffee Frappuccino is a coffee drink made by forcing hot water under high pressure through finely ground coffee beans.",
#   "stock": 10,
#   "price": 1.99,
#   "clasification_id": "650d0472b8b6303337f3905a"
# }



### GET ALL PRODUCTS
# GET http://localhost:4000/api/products?p=1&limit=5



### GET PRODUCT BY ID
# GET http://localhost:4000/api/products/650d08f2ecc24b20358b4ea1



### GET PRODUCTS BY CLASIFICATION
# GET http://localhost:4000/api/products/clasification/650d04fbb8b6303337f39062?p=1&limit=5



### UPDATE PRODUCT
# PUT http://localhost:4000/api/products/update/650d08f2ecc24b20358b4ea1
# Content-Type: application/json

# {
#   "name": "Natural Coffee Espresso",
#   "description": "Coffee Espresso is a coffee drink made by forcing hot water under high pressure through finely ground coffee beans.",
#   "stock": 25,
#   "price": 1.99,
#   "clasification_id": "650cc592013fa8252df78f1e"
# }



### DELETE PRODUCT
# DELETE http://localhost:4000/api/products/delete/650d08f2ecc24b20358b4ea1
